refactor(kubectl-grep): treat unset vars as error
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>

diff --git a/kubectl-grep b/kubectl-grep
--- a/kubectl-grep
+++ b/kubectl-grep
@@ -1,21 +1,28 @@
 #!/usr/bin/env bash
 
-set -o pipefail
+set -uo pipefail
+
+kubectl_grep() {
+	local res_name="${1:-}"
+	local res_type="${2:-}"
+
+	if [ -z "${res_name}" ]; then
+		echo "resource name is missing"
+		exit 1
+	fi
+
+	for r in $(kubectl api-resources -o name | grep -i "${res_type}" | grep -vE "^events$" )
+	do
+		res=$(kubectl get "${r}" -A 2>/dev/null | grep -i "${res_name}")
+		if ! [ -z "${res}" ]; then
+			echo; echo "${r}"
+			echo "${res}"
+		fi
+	done
+}
 
 main() {
-        if [ -z "${1}" ]; then
-                echo "resource name is missing"
-                exit 1
-        fi
-
-        for r in $(kubectl api-resources -o name | grep -i "${2}" | grep -vE "^events$" )
-        do
-                res=$(kubectl get "${r}" -A 2>/dev/null | grep -i "${1}")
-                if ! [ -z "${res}" ]; then
-                        echo; echo "${r}"
-                        echo "${res}"
-                fi
-        done
+	kubectl_grep $@
 }
 
 main $@
